version: '2'
services:
    server:
        build: .
        ports:
        - "8000:8000"
        depends_on:
        - database
    database:
        build: database
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=petstore
        ports:
        - "5432:5432"
